/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mpms;

import javax.swing.JOptionPane;
import mpms.data.Player;
import mpms.data.Transact;

/**
 *
 * @author rnagel
 */
public class PaymentDialog extends javax.swing.JDialog {
    private Player player = null;
    
    /**
     * Creates new form PaymentDialog
     * @param parent
     * @param player
     */
    public PaymentDialog(java.awt.Frame parent, Player player) {
        super(parent, true);
        initComponents();
        init(player);
        setLocationRelativeTo(parent);
    }
    public PaymentDialog(java.awt.Dialog parent, Player player) {
        super(parent, true);
        initComponents();
        init(player);
        setLocationRelativeTo(parent);
    }

    private void init(Player player)
    {
        this.player = player;
        lblName.setText(player.toString());
        txtBalance.setText(Global.DOLLARS.format(player.getBalance()));
        txtPayment.setText(Global.DOLLARS.format(player.getBalance()));
        txtPayment.requestFocus();
        txtPayment.selectAll();
    }
    
    private void confirmReceipt()
    {
        if (new String(pwdAuthenticate.getPassword()).equals(Global.AUTHENTICATION_PASSWORD))
        {
            String memo = txtMemo.getText();
            double amount = Global.normalizeMoneyAmount(txtPayment.getText());
            Transact payment = Transact.makePayment(player, amount, memo);
            player.updateToDatabase();
            JOptionPane.showMessageDialog(this, "Authentication succeeded.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Authentication failed.", "Error", JOptionPane.ERROR_MESSAGE);
            pwdAuthenticate.setText("");
            pwdAuthenticate.requestFocus();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        lblPayment = new javax.swing.JLabel();
        txtPayment = new javax.swing.JTextField();
        txtMemo = new javax.swing.JTextField();
        lblMemo = new javax.swing.JLabel();
        lblAuthenticate = new javax.swing.JLabel();
        pwdAuthenticate = new javax.swing.JPasswordField();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Make a Payment");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Player Name");

        lblBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBalance.setText("Current Balance:");

        txtBalance.setEditable(false);
        txtBalance.setBackground(new java.awt.Color(255, 255, 255));
        txtBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBalance.setForeground(new java.awt.Color(255, 0, 0));
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBalance.setText("$0.00");

        lblPayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPayment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPayment.setText("Your Payment:");

        txtPayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPayment.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPayment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaymentFocusLost(evt);
            }
        });

        txtMemo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblMemo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMemo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMemo.setText("Memo:");

        lblAuthenticate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAuthenticate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAuthenticate.setText("Authorization Password:");

        pwdAuthenticate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwdAuthenticate.setEchoChar('\u2022');
        pwdAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdAuthenticateActionPerformed(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirm.setText("Authorize");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMemo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAuthenticate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pwdAuthenticate)
                                    .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPayment))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMemo, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalance)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPayment)
                    .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMemo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAuthenticate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdAuthenticate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        confirmReceipt();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void pwdAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdAuthenticateActionPerformed
        confirmReceipt();
    }//GEN-LAST:event_pwdAuthenticateActionPerformed

    private void txtPaymentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaymentFocusLost
        try {
            double payment = Double.parseDouble(txtPayment.getText());
            if (payment < 0)
            {
                if (txtMemo.getText().equalsIgnoreCase("payment"))
                {
                    txtMemo.setText("charge");
                }
            }
            else
            {
                if(txtMemo.getText().equalsIgnoreCase("charge"))
                {
                    txtMemo.setText("payment");
                }
            }
        } catch (Exception ex)
        {
        }
    }//GEN-LAST:event_txtPaymentFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblAuthenticate;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblMemo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JPasswordField pwdAuthenticate;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtMemo;
    private javax.swing.JTextField txtPayment;
    // End of variables declaration//GEN-END:variables
}
