/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import mpms.data.Charge;
import mpms.data.Lesson;
import mpms.data.Player;
import mpms.data.Transact;
import mpms.data.Visit;

/**
 *
 * @author rnagel
 */
public final class PlayerAccountDialog extends javax.swing.JDialog
{
    private Player player = null;
    private boolean firstTime = false;
    private boolean alreadyCheckedIn = false;
    private boolean alreadyHadLesson = false;
    private boolean autoVisitCharge = false;
    private int lessonIndex = 1;

    /**
     * Creates new form PlayerAccountDialog
     * @param parent
     * @param player
     */
    public PlayerAccountDialog(java.awt.Frame parent, Player player)
    {
        super(parent, true);
        initComponents();
        
        initialize(player);
        setLocationRelativeTo(parent);
    }
    
    public void initialize(Player player)
    {
        this.player = player;
        firstTime = false;
        alreadyCheckedIn = false;
        alreadyHadLesson = false;
        autoVisitCharge = false;        
        
        lblPlayerHeading.setText(player.toString());
        txtBalance.setText(Global.DOLLARS.format(player.getBalance()));
        txtVisits.setText(player.getVisits()+"");
        btnMakePayment.setEnabled(player.getSponsorId()==null);
        
        firstTime = player.getVisitRecords().isEmpty();
        alreadyCheckedIn = player.checkedInToday();
        alreadyHadLesson = player.hadLessonToday();
        lessonIndex = player.getLessonsThisWeek()+1;
        
        int visits = player.getVisits();
        
        btnCancel.setVisible(false);
        btnCheckIn.setVisible(false);
        btnOk.setVisible(false);
        btnLesson.setVisible(false);   
        btnLesson.setText("Lesson (" + Global.DOLLARS.format(Global.getPriceForLessonIndex(lessonIndex)) + ")");
        
        if (alreadyCheckedIn)
        {
            lblCheckInMessage.setText("You have already checked in for today.");     
            btnOk.setVisible(true);
            if (!alreadyHadLesson)
            {
                btnLesson.setVisible(true);
            }            
        }
        else
        {
            btnCancel.setVisible(true);
            btnCheckIn.setVisible(true);
            btnLesson.setVisible(true);
            if (firstTime)
            {
                lblCheckInMessage.setText("Welcome! Your first visit is on us. Check in to play for free today!");
                btnCheckIn.setText("Check In (free)");
            }
            else if (visits > 0)
            {
                lblCheckInMessage.setText("Welcome back. When you check in, your account will be debited 1 visit.");
                btnCheckIn.setText("Check In (-1 Visit)");
            }
            else
            {
                lblCheckInMessage.setText("You have no visits remaining. A $5 charge will be applied when you check in.");
                btnCheckIn.setText("Check In ($5.00)");
                autoVisitCharge = true;
            }
        }
    }

    
    
    private boolean transferBalanceToSponsor()
    {
        if (player.getSponsorId() != null && player.getBalance() > 0)
        {
            try {
                Player sponsor = Player.fromDatabase(player.getSponsorId());
                double balance = player.getBalance();
                
                Transact.arrangeTransfer(player, sponsor, balance, "Sponsorship: ");
                                
                player.updateToDatabase();
                sponsor.updateToDatabase();
                initialize(player);
                
                return true;
                
            } catch (SQLException ex) {
                Logger.getLogger(PlayerAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
        }
        return false;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlayerHeading = new javax.swing.JLabel();
        pnlAccount = new javax.swing.JPanel();
        lblBalance = new javax.swing.JLabel();
        lblVisits = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        txtVisits = new javax.swing.JTextField();
        btnMakePayment = new javax.swing.JButton();
        btnRechargeVisits = new javax.swing.JButton();
        btnViewTransactions = new javax.swing.JButton();
        btnEditAccountInfo = new javax.swing.JButton();
        pnlCheckIn = new javax.swing.JPanel();
        lblCheckInMessage = new javax.swing.JLabel();
        pnlCenterCheckInButton = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnLesson = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Player Account");

        lblPlayerHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPlayerHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerHeading.setText("[0] Lastname, Firstname");

        pnlAccount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lblBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBalance.setText("Current Balance:");

        lblVisits.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVisits.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVisits.setText("Remaining Visits:");

        txtBalance.setEditable(false);
        txtBalance.setBackground(new java.awt.Color(255, 255, 255));
        txtBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBalance.setText("$0.00");

        txtVisits.setEditable(false);
        txtVisits.setBackground(new java.awt.Color(255, 255, 255));
        txtVisits.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVisits.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVisits.setText("0");

        btnMakePayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMakePayment.setText("Make Payment");
        btnMakePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakePaymentActionPerformed(evt);
            }
        });

        btnRechargeVisits.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRechargeVisits.setText("Recharge");
        btnRechargeVisits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechargeVisitsActionPerformed(evt);
            }
        });

        btnViewTransactions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewTransactions.setText("View Transaction History");
        btnViewTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTransactionsActionPerformed(evt);
            }
        });

        btnEditAccountInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditAccountInfo.setText("Edit Account Info");
        btnEditAccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAccountInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccountLayout = new javax.swing.GroupLayout(pnlAccount);
        pnlAccount.setLayout(pnlAccountLayout);
        pnlAccountLayout.setHorizontalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVisits, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtVisits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMakePayment, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnRechargeVisits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditAccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAccountLayout.setVerticalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBalance)
                        .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMakePayment))
                    .addComponent(btnEditAccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVisits)
                        .addComponent(txtVisits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRechargeVisits))
                    .addComponent(btnViewTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAccountLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMakePayment, btnRechargeVisits});

        pnlCheckIn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lblCheckInMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCheckInMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCheckInMessage.setText("Check In Message.");

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(153, 0, 0));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlCenterCheckInButton.add(btnCancel);

        btnCheckIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheckIn.setForeground(new java.awt.Color(0, 153, 0));
        btnCheckIn.setText("Check In to Play");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });
        pnlCenterCheckInButton.add(btnCheckIn);

        btnOk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        pnlCenterCheckInButton.add(btnOk);

        btnLesson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLesson.setForeground(new java.awt.Color(0, 0, 204));
        btnLesson.setText("Lesson");
        btnLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLessonActionPerformed(evt);
            }
        });
        pnlCenterCheckInButton.add(btnLesson);

        javax.swing.GroupLayout pnlCheckInLayout = new javax.swing.GroupLayout(pnlCheckIn);
        pnlCheckIn.setLayout(pnlCheckInLayout);
        pnlCheckInLayout.setHorizontalGroup(
            pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCheckInMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCenterCheckInButton, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCheckInLayout.setVerticalGroup(
            pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCheckInMessage)
                .addGap(18, 18, 18)
                .addComponent(pnlCenterCheckInButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayerHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayerHeading)
                .addGap(18, 18, 18)
                .addComponent(pnlAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCheckInActionPerformed
    {//GEN-HEADEREND:event_btnCheckInActionPerformed
        // If the Player had no Visits to use, buy one and use it immediately:
        if (autoVisitCharge)
        {
            Charge charge = Charge.makeCharge(player, 5.0, "Daily Visit Fee");
            player.addVisits(1);
        }

        // Put a new Visit record in the database:        
        Visit visit = Visit.makeVisit(player);
        MpmsMain.Database.insertVisit(visit);
        
        // Debit a visit from the account:
        if (!firstTime)
        {
            player.spendVisit();            
        }        
        
        // Update Player in the database:
        player.updateToDatabase();
        
        // Play sound:
        Global.playSound("check_in");
        
        // Close this dialog:        
        this.setVisible(false);
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        // Close this dialog and do nothing:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLessonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLessonActionPerformed
    {//GEN-HEADEREND:event_btnLessonActionPerformed
        // Put a new Lesson record in the database:
        Lesson lesson = Lesson.makeLesson(player);
        MpmsMain.Database.insertLesson(lesson);
        
        // If the Player was already checked in, refund the Visit:
        if (alreadyCheckedIn)
        {
            player.addVisits(1);            
        }
        else
        {
            // Put a new Visit record in the database.   
            Visit visit = Visit.makeVisit(player);
            MpmsMain.Database.insertVisit(visit);
        }
        
        // Add a charge to this account for the lesson ($12 for first, $10 for second, $8 for third):
        double amount = Global.getPriceForLessonIndex(lessonIndex);
        String description = lessonIndex == 1 ? "1st" : (lessonIndex == 2 ? "2nd" : "3rd");
        Charge charge = Charge.makeCharge(player, amount, description + " lesson");
        
        // Update Player in the database:
        player.updateToDatabase();
        
        // Play sound:
        Global.playSound("lesson");
        
        // Show Purchase Confirmation:
        PurchaseConfirmDialog purchaseDlg = new PurchaseConfirmDialog(this, player, charge);
        purchaseDlg.setVisible(true);
        
        // Close this dialog:
        this.setVisible(false);
    }//GEN-LAST:event_btnLessonActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOkActionPerformed
    {//GEN-HEADEREND:event_btnOkActionPerformed
        // Close this dialog and do nothing:
        this.setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnEditAccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAccountInfoActionPerformed
        EditPlayerDialog editDlg = new EditPlayerDialog(this);
        editDlg.initialize(player);
        editDlg.setVisible(true);
        
        if (!transferBalanceToSponsor()) // If true is returned, the player has already been updated, along with the sponsor.
        {
            player.updateToDatabase();
        }
        
    }//GEN-LAST:event_btnEditAccountInfoActionPerformed

    private void btnMakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePaymentActionPerformed
        PaymentDialog paymentDlg = new PaymentDialog(this, player);
        paymentDlg.setVisible(true);        
        initialize(player);
    }//GEN-LAST:event_btnMakePaymentActionPerformed

    private void btnRechargeVisitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechargeVisitsActionPerformed
        RechargeVisitsDialog rechargeDlg = new RechargeVisitsDialog(this, player);
        rechargeDlg.setVisible(true);
        initialize(player);
    }//GEN-LAST:event_btnRechargeVisitsActionPerformed

    private void btnViewTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTransactionsActionPerformed
        PlayerTransactHistoryDialog transDlg = new PlayerTransactHistoryDialog(this, player);
        transDlg.setVisible(true);
    }//GEN-LAST:event_btnViewTransactionsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnEditAccountInfo;
    private javax.swing.JButton btnLesson;
    private javax.swing.JButton btnMakePayment;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRechargeVisits;
    private javax.swing.JButton btnViewTransactions;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblCheckInMessage;
    private javax.swing.JLabel lblPlayerHeading;
    private javax.swing.JLabel lblVisits;
    private javax.swing.JPanel pnlAccount;
    private javax.swing.JPanel pnlCenterCheckInButton;
    private javax.swing.JPanel pnlCheckIn;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtVisits;
    // End of variables declaration//GEN-END:variables
}
