/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mpms;

import javax.swing.JOptionPane;
import mpms.data.Charge;
import mpms.data.Player;
import mpms.data.Transact;

/**
 *
 * @author rnagel
 */
public class RechargeVisitsDialog extends javax.swing.JDialog {
    private Player player = null;
    
    /**
     * Creates new form PaymentDialog
     * @param parent
     * @param player
     */
    public RechargeVisitsDialog(java.awt.Frame parent, Player player) {
        super(parent, true);
        initComponents();
        init(player);
        setLocationRelativeTo(parent);
    }
    public RechargeVisitsDialog(java.awt.Dialog parent, Player player) {
        super(parent, true);
        initComponents();
        init(player);
        setLocationRelativeTo(parent);
    }

    private void init(Player player)
    {
        this.player = player;
        lblName.setText(player.toString());
        txtCurrentVisits.setText(player.getVisits()+"");
        updatePurchase();
    }
    
    private void updatePurchase()
    {
        int visits = sldPurchase.getValue();
        double rate = 0.0;
        lblRate1.setEnabled(false);
        lblRate5.setEnabled(false);
        lblRate10.setEnabled(false);
        lblRate25.setEnabled(false);
        lblRate50.setEnabled(false);
        if (visits == 50)
        {
            lblRate50.setEnabled(true);
            rate = 2.5;
        }
        else if (visits >= 25)
        {
            lblRate25.setEnabled(true);
            rate = 3.0;
        }
        else if (visits >= 10)
        {
            lblRate10.setEnabled(true);
            rate = 3.5;
        }
        else if (visits >= 5)
        {
            lblRate5.setEnabled(true);
            rate = 4.0;
        }
        else if (visits >= 1)
        {
            lblRate1.setEnabled(true);
            rate = 5.0;
        }
        
        double price = rate*(double)visits;
        double dailyTotal = 5.00 * (double)visits;
        double savings = dailyTotal - price;
        
        txtPurchase.setText(visits+"");
        txtRate.setText(Global.DOLLARS.format(rate));
        txtPrice.setText(Global.DOLLARS.format(price));
        
        if (visits == 0)
        {
            lblSummary.setText("Use the slider to select an amount of visits for purchase.");
            btnPurchase.setEnabled(false);
        }
        else
        {            
            lblSummary.setText("Your purchase of " + visits + " visits for " + Global.DOLLARS.format(price) + " will save you " + Global.DOLLARS.format(savings) + " vs. paying the daily rate.");
            btnPurchase.setEnabled(true);
        }
                
    }
    
    private void purchase()
    {        
        String memo = sldPurchase.getValue() + " Visits @ " + txtRate.getText();
        double amount = Global.normalizeMoneyAmount(txtPrice.getText());
        Charge charge = Charge.makeCharge(player, amount, memo);
        player.addVisits(sldPurchase.getValue());
        player.updateToDatabase();

        PurchaseConfirmDialog purchaseDlg = new PurchaseConfirmDialog(this, player, charge);
        purchaseDlg.setVisible(true);
        setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        pnlCenterPurchaseVisits = new javax.swing.JPanel();
        pnlContPurchaseVisits = new javax.swing.JPanel();
        lblAt = new javax.swing.JLabel();
        lblPurchase = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        txtPurchase = new javax.swing.JTextField();
        lblEquals = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        pnlCenterCurrentVisits = new javax.swing.JPanel();
        pnlContCurrentVisits = new javax.swing.JPanel();
        txtCurrentVisits = new javax.swing.JTextField();
        lblCurrentVisits = new javax.swing.JLabel();
        pnlPurchaseSlider = new javax.swing.JPanel();
        sldPurchase = new javax.swing.JSlider();
        lblRate1 = new javax.swing.JLabel();
        lblRate5 = new javax.swing.JLabel();
        lblRate10 = new javax.swing.JLabel();
        lblRate25 = new javax.swing.JLabel();
        lblRate50 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        lblTotal5 = new javax.swing.JLabel();
        lblTotal10 = new javax.swing.JLabel();
        lblTotal25 = new javax.swing.JLabel();
        lblTotal50 = new javax.swing.JLabel();
        lblSummary = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Purchase Visits");
        setResizable(false);

        lblName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Player Name");

        lblAt.setText("@");

        lblPurchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPurchase.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPurchase.setText("Visits to Purchase:");

        txtRate.setEditable(false);
        txtRate.setBackground(new java.awt.Color(255, 255, 255));
        txtRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRate.setText("$0.00");

        txtPurchase.setEditable(false);
        txtPurchase.setBackground(new java.awt.Color(255, 255, 255));
        txtPurchase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPurchase.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPurchase.setText("0");

        lblEquals.setText("=");

        txtPrice.setEditable(false);
        txtPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrice.setText("$0.00");

        javax.swing.GroupLayout pnlContPurchaseVisitsLayout = new javax.swing.GroupLayout(pnlContPurchaseVisits);
        pnlContPurchaseVisits.setLayout(pnlContPurchaseVisitsLayout);
        pnlContPurchaseVisitsLayout.setHorizontalGroup(
            pnlContPurchaseVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContPurchaseVisitsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRate, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEquals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlContPurchaseVisitsLayout.setVerticalGroup(
            pnlContPurchaseVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContPurchaseVisitsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContPurchaseVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlContPurchaseVisitsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblEquals))
                    .addComponent(txtPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlContPurchaseVisitsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblAt))
                    .addGroup(pnlContPurchaseVisitsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPurchase)))
                .addContainerGap())
        );

        pnlContPurchaseVisitsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtPurchase, txtRate});

        pnlCenterPurchaseVisits.add(pnlContPurchaseVisits);

        txtCurrentVisits.setEditable(false);
        txtCurrentVisits.setBackground(new java.awt.Color(255, 255, 255));
        txtCurrentVisits.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCurrentVisits.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCurrentVisits.setText("0");

        lblCurrentVisits.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentVisits.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCurrentVisits.setText("Current Visits:");

        javax.swing.GroupLayout pnlContCurrentVisitsLayout = new javax.swing.GroupLayout(pnlContCurrentVisits);
        pnlContCurrentVisits.setLayout(pnlContCurrentVisitsLayout);
        pnlContCurrentVisitsLayout.setHorizontalGroup(
            pnlContCurrentVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContCurrentVisitsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentVisits)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCurrentVisits, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlContCurrentVisitsLayout.setVerticalGroup(
            pnlContCurrentVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContCurrentVisitsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContCurrentVisitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentVisits)
                    .addComponent(txtCurrentVisits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlCenterCurrentVisits.add(pnlContCurrentVisits);

        pnlPurchaseSlider.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sldPurchase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sldPurchase.setMajorTickSpacing(5);
        sldPurchase.setMaximum(50);
        sldPurchase.setMinorTickSpacing(1);
        sldPurchase.setPaintTicks(true);
        sldPurchase.setValue(0);
        sldPurchase.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPurchaseStateChanged(evt);
            }
        });

        lblRate1.setText("<html>1 Visit<br>$5.00/each");
        lblRate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRate1MousePressed(evt);
            }
        });

        lblRate5.setText("<html>5+ Visits<br>$4.00/each");
        lblRate5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRate5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRate5MousePressed(evt);
            }
        });

        lblRate10.setText("<html>10+ Visits<br>$3.50/each");
        lblRate10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRate10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRate10MousePressed(evt);
            }
        });

        lblRate25.setText("<html>25+ Visits<br>$3.00/each");
        lblRate25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRate25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRate25MousePressed(evt);
            }
        });

        lblRate50.setText("<html>50 Visits<br>$2.50/each");
        lblRate50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRate50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRate50MousePressed(evt);
            }
        });

        lblTotal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal1.setText("$5.00");
        lblTotal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTotal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTotal1MousePressed(evt);
            }
        });

        lblTotal5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal5.setText("$20.00");
        lblTotal5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTotal5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTotal5MousePressed(evt);
            }
        });

        lblTotal10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal10.setText("$35.00");
        lblTotal10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTotal10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTotal10MousePressed(evt);
            }
        });

        lblTotal25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal25.setText("$75.00");
        lblTotal25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTotal25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTotal25MousePressed(evt);
            }
        });

        lblTotal50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal50.setText("$125.00");
        lblTotal50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTotal50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTotal50MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlPurchaseSliderLayout = new javax.swing.GroupLayout(pnlPurchaseSlider);
        pnlPurchaseSlider.setLayout(pnlPurchaseSliderLayout);
        pnlPurchaseSliderLayout.setHorizontalGroup(
            pnlPurchaseSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPurchaseSliderLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(sldPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(pnlPurchaseSliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPurchaseSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal1)
                    .addComponent(lblRate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPurchaseSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPurchaseSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal10)
                    .addComponent(lblRate10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156)
                .addGroup(pnlPurchaseSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRate25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPurchaseSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal50)
                    .addComponent(lblRate50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pnlPurchaseSliderLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblRate1, lblTotal1});

        pnlPurchaseSliderLayout.setVerticalGroup(
            pnlPurchaseSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPurchaseSliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPurchaseSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRate10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRate25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRate50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPurchaseSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal1)
                    .addComponent(lblTotal5)
                    .addComponent(lblTotal10)
                    .addComponent(lblTotal25)
                    .addComponent(lblTotal50))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSummary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSummary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSummary.setText("Your purchase of _ visits for _ will save you _ vs. paying the daily rate.");

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        btnPurchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPurchase.setText("Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });
        jPanel1.add(btnPurchase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCenterCurrentVisits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCenterPurchaseVisits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPurchaseSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCenterCurrentVisits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCenterPurchaseVisits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPurchaseSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        purchase();
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void sldPurchaseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPurchaseStateChanged
        updatePurchase();
    }//GEN-LAST:event_sldPurchaseStateChanged

    private void lblTotal1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotal1MousePressed
        sldPurchase.setValue(1);
    }//GEN-LAST:event_lblTotal1MousePressed

    private void lblTotal5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotal5MousePressed
        sldPurchase.setValue(5);
    }//GEN-LAST:event_lblTotal5MousePressed

    private void lblTotal10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotal10MousePressed
        sldPurchase.setValue(10);
    }//GEN-LAST:event_lblTotal10MousePressed

    private void lblTotal25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotal25MousePressed
        sldPurchase.setValue(25);
    }//GEN-LAST:event_lblTotal25MousePressed

    private void lblTotal50MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotal50MousePressed
        sldPurchase.setValue(50);
    }//GEN-LAST:event_lblTotal50MousePressed

    private void lblRate1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRate1MousePressed
        sldPurchase.setValue(1);
    }//GEN-LAST:event_lblRate1MousePressed

    private void lblRate5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRate5MousePressed
        sldPurchase.setValue(5);
    }//GEN-LAST:event_lblRate5MousePressed

    private void lblRate10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRate10MousePressed
        sldPurchase.setValue(10);
    }//GEN-LAST:event_lblRate10MousePressed

    private void lblRate25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRate25MousePressed
        sldPurchase.setValue(25);
    }//GEN-LAST:event_lblRate25MousePressed

    private void lblRate50MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRate50MousePressed
        sldPurchase.setValue(50);
    }//GEN-LAST:event_lblRate50MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAt;
    private javax.swing.JLabel lblCurrentVisits;
    private javax.swing.JLabel lblEquals;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPurchase;
    private javax.swing.JLabel lblRate1;
    private javax.swing.JLabel lblRate10;
    private javax.swing.JLabel lblRate25;
    private javax.swing.JLabel lblRate5;
    private javax.swing.JLabel lblRate50;
    private javax.swing.JLabel lblSummary;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal10;
    private javax.swing.JLabel lblTotal25;
    private javax.swing.JLabel lblTotal5;
    private javax.swing.JLabel lblTotal50;
    private javax.swing.JPanel pnlCenterCurrentVisits;
    private javax.swing.JPanel pnlCenterPurchaseVisits;
    private javax.swing.JPanel pnlContCurrentVisits;
    private javax.swing.JPanel pnlContPurchaseVisits;
    private javax.swing.JPanel pnlPurchaseSlider;
    private javax.swing.JSlider sldPurchase;
    private javax.swing.JTextField txtCurrentVisits;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPurchase;
    private javax.swing.JTextField txtRate;
    // End of variables declaration//GEN-END:variables
}
