/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mpms;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import mpms.data.Player;
import mpms.data.Transact;

/**
 *
 * @author rnagel
 */
public class RefundDialog extends javax.swing.JDialog {
    private Player player = null;
    
    /**
     * Creates new form RefundDialog
     * @param parent
     */
    public RefundDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        init();
    }
    public RefundDialog(java.awt.Dialog parent) {
        super(parent, true);
        initComponents();        
        setLocationRelativeTo(parent);
        init();
    }

    private void init()
    {        
        pdPlayer.loadPlayersByLetter('*');
        this.player = pdPlayer.getSelectedPlayer();        
        pdPlayer.addActionListener((ActionEvent e) -> {
            this.player = pdPlayer.getSelectedPlayer();
            txtBalance.setText(Global.DOLLARS.format(player.getBalance()));
            txtRefund.requestFocus();
        });
    }
    
    private void confirmReceipt()
    {
        if (new String(pwdAuthenticate.getPassword()).equals(Global.AUTHENTICATION_PASSWORD))
        {
            String memo = txtMemo.getText();
            double amount = Global.normalizeMoneyAmount(txtRefund.getText());
            Transact refund = Transact.makeRefund(player, amount, memo);
            player.updateToDatabase();
            JOptionPane.showMessageDialog(this, "Authentication succeeded.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Authentication failed.", "Error", JOptionPane.ERROR_MESSAGE);
            pwdAuthenticate.setText("");
            pwdAuthenticate.requestFocus();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBalance = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        lblRefund = new javax.swing.JLabel();
        txtRefund = new javax.swing.JTextField();
        txtMemo = new javax.swing.JTextField();
        lblMemo = new javax.swing.JLabel();
        lblAuthenticate = new javax.swing.JLabel();
        pwdAuthenticate = new javax.swing.JPasswordField();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pdPlayer = new mpms.PlayerDirectory();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Issue a Refund");

        lblBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBalance.setText("Current Balance:");

        txtBalance.setEditable(false);
        txtBalance.setBackground(new java.awt.Color(255, 255, 255));
        txtBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBalance.setForeground(new java.awt.Color(255, 0, 0));
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBalance.setText("$0.00");

        lblRefund.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRefund.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRefund.setText("Refund Amount:");

        txtRefund.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRefund.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRefund.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRefundFocusLost(evt);
            }
        });

        txtMemo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblMemo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMemo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMemo.setText("Memo:");

        lblAuthenticate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAuthenticate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAuthenticate.setText("Authorization Password:");

        pwdAuthenticate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwdAuthenticate.setEchoChar('\u2022');
        pwdAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdAuthenticateActionPerformed(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirm.setText("Authorize");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMemo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pwdAuthenticate)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblMemo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAuthenticate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pdPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRefund, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRefund))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pdPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalance)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRefund)
                    .addComponent(txtRefund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMemo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAuthenticate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdAuthenticate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        confirmReceipt();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void pwdAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdAuthenticateActionPerformed
        confirmReceipt();
    }//GEN-LAST:event_pwdAuthenticateActionPerformed

    private void txtRefundFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefundFocusLost
        try {
            double payment = Double.parseDouble(txtRefund.getText());
            if (payment < 0)
            {
                if (txtMemo.getText().equalsIgnoreCase("payment"))
                {
                    txtMemo.setText("charge");
                }
            }
            else
            {
                if(txtMemo.getText().equalsIgnoreCase("charge"))
                {
                    txtMemo.setText("payment");
                }
            }
        } catch (Exception ex)
        {
        }
    }//GEN-LAST:event_txtRefundFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblAuthenticate;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblMemo;
    private javax.swing.JLabel lblRefund;
    private mpms.PlayerDirectory pdPlayer;
    private javax.swing.JPasswordField pwdAuthenticate;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtMemo;
    private javax.swing.JTextField txtRefund;
    // End of variables declaration//GEN-END:variables
}
