/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpms;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import mpms.data.Player;

/**
 *
 * @author Ray
 */
public class SponsorshipDialog extends javax.swing.JDialog {

    private Player player = null;
    private Player sponsor = null;
    
    /**
     * Creates new form SponsorshipDialog
     * @param parent
     * @param player
     * @param sponsorId
     */
    public SponsorshipDialog(java.awt.Dialog parent, Player player, Integer sponsorId) {
        super(parent, true);
        initComponents();
        pdSponsor.addActionListener((ActionEvent e) -> {
            if (pdSponsor.getSelectedPlayer() != null)
            {
                lblExplanation.setText(pdSponsor.getSelectedPlayer().getFirstName() + " will be responsible for paying all charges incurred by " + player.getFirstName() + ".");
            }
        });
        init(player, sponsorId);
        setLocationRelativeTo(parent);
    }

    private void init(Player player, Integer sponsorId)
    {
        this.player = player;
        lblTitle.setText("Select sponsor for " + player.toString() + ":");        
        pdSponsor.setSelectedPlayer(sponsorId == null ? player.getId() : sponsorId);
        if (pdSponsor.getSelectedPlayer() != null)
        {
            lblExplanation.setText(pdSponsor.getSelectedPlayer().getFirstName() + " will be responsible for paying all charges incurred by " + player.getFirstName() + ".");
        }
    }
    
    private void authenticate()
    {
        if (new String(pwdAuthenticate.getPassword()).equals(Global.AUTHENTICATION_PASSWORD))
        {
            this.sponsor = pdSponsor.getSelectedPlayer();
            JOptionPane.showMessageDialog(this, "Authentication succeeded.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Authentication failed.", "Error", JOptionPane.ERROR_MESSAGE);
            pwdAuthenticate.setText("");
            pwdAuthenticate.requestFocus();
        }
    }
    
    public Player getSponsor()
    {
        return this.sponsor;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        pdSponsor = new mpms.PlayerDirectory();
        lblAuthenticate = new javax.swing.JLabel();
        pwdAuthenticate = new javax.swing.JPasswordField();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblExplanation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sponsorship");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("Select sponsor for _:");

        lblAuthenticate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAuthenticate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAuthenticate.setText("Authorization Password:");

        pwdAuthenticate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwdAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdAuthenticateActionPerformed(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirm.setText("Authorize");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblExplanation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExplanation.setText("_ will be responsible for paying all charges incurred by _.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTitle)
                    .addComponent(pwdAuthenticate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pdSponsor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblExplanation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAuthenticate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(pdSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblExplanation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lblAuthenticate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdAuthenticate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdAuthenticateActionPerformed
        authenticate();
    }//GEN-LAST:event_pwdAuthenticateActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        authenticate();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblAuthenticate;
    private javax.swing.JLabel lblExplanation;
    private javax.swing.JLabel lblTitle;
    private mpms.PlayerDirectory pdSponsor;
    private javax.swing.JPasswordField pwdAuthenticate;
    // End of variables declaration//GEN-END:variables
}
